# Generated by Django 4.2.16 on 2024-11-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='verification_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
